source 'https://rubygems.org'



gem 'dotenv-rails'
gem 'bootstrap-sass'
gem 'bootstrap-tooltip-rails'
gem 'bootstrap_helper'
gem 'coffee-rails'
gem 'compass-rails'
gem 'devise'
gem 'jbuilder'
gem 'jquery-migrate-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'json'
gem 'pg'
gem 'rails', '4.2.5.1'
gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'therubyracer'
gem 'uglifier'
gem 'unicorn'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'fuubar'
  gem 'growl'
  gem 'guard-rspec'
  gem 'htmlbeautifier'
  gem 'launchy'
  gem 'meta_request'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rack-mini-profiler'
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'spring-commands-rspec'
  gem 'terminal-notifier-guard'
  gem 'valid_attribute'
end
